
package fonts;

import fonts.CalcBMISection;
import java.text.*;
import javax.swing.JPanel;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.*;
import main.StartScreen;



/**
 *
 * @author MANUEL JAIME
 */
public class BMI_Section extends javax.swing.JFrame {

    /**
     * Creates new form BMI_Section
     */
    public BMI_Section() {
        initComponents();
        
         // try...catch para a fonte geral
        try {
            File font_family = new File("src/fonts/Outfit-Regular.ttf");
            
            Font font_buttons = Font.createFont(Font.TRUETYPE_FONT,font_family).deriveFont(16f);
            Font font_inputs = Font.createFont(Font.TRUETYPE_FONT,font_family).deriveFont(16f);
            Font font_labels = Font.createFont(Font.TRUETYPE_FONT,font_family).deriveFont(16f);
            
                        
            calcIMC_btn.setFont(font_labels);
            back_btn.setFont(font_labels);
            
            altura_input.setFont(font_labels);
            peso_input.setFont(font_labels);
            IMCResult_label.setFont(font_labels);
            IMC_Avaluation_label.setFont(font_labels);
                   

            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        // try...catch para fonte de subtitulo
        try {
            File font_family_bold = new File("src/fonts/Outfit-Bold.ttf");
            Font font_subtitle = Font.createFont(Font.TRUETYPE_FONT,font_family_bold).deriveFont(32f);
            label_title.setFont(font_subtitle);
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        // try...catch para fonte de resultado e avaliação
        try {
            File font_family_bold = new File("src/fonts/Outfit-Bold.ttf");
            Font font_result = Font.createFont(Font.TRUETYPE_FONT,font_family_bold).deriveFont(24f);
            Font font_avaluation = Font.createFont(Font.TRUETYPE_FONT,font_family_bold).deriveFont(18f);
            
            IMC_label.setFont(font_result);
            IMCResult_label.setFont(font_result);
            IMC_Avaluation_label.setFont(font_avaluation);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     void changeColor(JPanel hover, Color rand ){
        hover.setBackground(rand);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        header = new javax.swing.JPanel();
        close_max_min_group = new javax.swing.JPanel();
        close_btn = new javax.swing.JPanel();
        close_icon = new javax.swing.JLabel();
        max_btn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        min_btn = new javax.swing.JPanel();
        min_icon = new javax.swing.JLabel();
        container2 = new javax.swing.JPanel();
        back_btn = new javax.swing.JButton();
        img_container2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        label_title = new javax.swing.JLabel();
        altura_label = new javax.swing.JLabel();
        altura_input = new javax.swing.JTextField();
        peso_input = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        calcIMC_btn = new javax.swing.JButton();
        div_top = new javax.swing.JLabel();
        IMC_Avaluation_label = new javax.swing.JLabel();
        IMC_label = new javax.swing.JLabel();
        IMCResult_label = new javax.swing.JLabel();
        div_bottom = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BMI Calculator - por Manuel Jaime");
        setUndecorated(true);
        setResizable(false);

        header.setBackground(new java.awt.Color(73, 158, 59));
        header.setPreferredSize(new java.awt.Dimension(800, 50));
        header.setRequestFocusEnabled(false);

        close_max_min_group.setBackground(new java.awt.Color(107, 190, 89));
        close_max_min_group.setPreferredSize(new java.awt.Dimension(150, 50));

        close_btn.setBackground(new java.awt.Color(107, 190, 89));
        close_btn.setPreferredSize(new java.awt.Dimension(50, 50));
        close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close_btnMouseExited(evt);
            }
        });
        close_btn.setLayout(new java.awt.BorderLayout());

        close_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fechar.png"))); // NOI18N
        close_btn.add(close_icon, java.awt.BorderLayout.CENTER);

        max_btn.setBackground(new java.awt.Color(107, 190, 89));
        max_btn.setPreferredSize(new java.awt.Dimension(50, 50));
        max_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                max_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                max_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                max_btnMouseExited(evt);
            }
        });
        max_btn.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/maximize-o-tamanho.png"))); // NOI18N
        max_btn.add(jLabel2, java.awt.BorderLayout.CENTER);

        min_btn.setBackground(new java.awt.Color(107, 190, 89));
        min_btn.setPreferredSize(new java.awt.Dimension(50, 50));
        min_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                min_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                min_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                min_btnMouseExited(evt);
            }
        });
        min_btn.setLayout(new java.awt.BorderLayout());

        min_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menos.png"))); // NOI18N
        min_btn.add(min_icon, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout close_max_min_groupLayout = new javax.swing.GroupLayout(close_max_min_group);
        close_max_min_group.setLayout(close_max_min_groupLayout);
        close_max_min_groupLayout.setHorizontalGroup(
            close_max_min_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, close_max_min_groupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(min_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(max_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        close_max_min_groupLayout.setVerticalGroup(
            close_max_min_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(close_max_min_groupLayout.createSequentialGroup()
                .addGroup(close_max_min_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(max_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(min_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 732, Short.MAX_VALUE)
                .addComponent(close_max_min_group, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close_max_min_group, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        container2.setBackground(new java.awt.Color(255, 255, 255));

        back_btn.setBackground(new java.awt.Color(26, 185, 33));
        back_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setText("Voltar");
        back_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        img_container2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modified/imc-section-img.png"))); // NOI18N

        javax.swing.GroupLayout img_container2Layout = new javax.swing.GroupLayout(img_container2);
        img_container2.setLayout(img_container2Layout);
        img_container2Layout.setHorizontalGroup(
            img_container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        img_container2Layout.setVerticalGroup(
            img_container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        content.setBackground(new java.awt.Color(51, 51, 51));

        label_title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_title.setForeground(new java.awt.Color(51, 204, 0));
        label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_title.setText("Vamos Calcular o seu IMC !");

        altura_label.setBackground(new java.awt.Color(255, 255, 255));
        altura_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        altura_label.setForeground(new java.awt.Color(255, 255, 255));
        altura_label.setText("Altura (cm)");

        altura_input.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        altura_input.setText("0");
        altura_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                altura_inputKeyTyped(evt);
            }
        });

        peso_input.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        peso_input.setText("0");
        peso_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peso_inputActionPerformed(evt);
            }
        });
        peso_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                peso_inputKeyTyped(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Peso (kg)");

        calcIMC_btn.setBackground(new java.awt.Color(51, 153, 0));
        calcIMC_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        calcIMC_btn.setForeground(new java.awt.Color(255, 255, 255));
        calcIMC_btn.setText("Calcular");
        calcIMC_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcIMC_btnActionPerformed(evt);
            }
        });
        calcIMC_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                calcIMC_btnKeyPressed(evt);
            }
        });

        div_top.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        IMC_Avaluation_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IMC_Avaluation_label.setForeground(new java.awt.Color(255, 255, 255));
        IMC_Avaluation_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IMC_Avaluation_label.setText("Avaliação:");

        IMC_label.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        IMC_label.setForeground(new java.awt.Color(255, 255, 255));
        IMC_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IMC_label.setText("IMC :");

        IMCResult_label.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        IMCResult_label.setForeground(new java.awt.Color(255, 255, 255));
        IMCResult_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IMCResult_label.setText("0");

        div_bottom.setForeground(new java.awt.Color(255, 255, 255));
        div_bottom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(label_title)
                    .addComponent(altura_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(altura_input, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peso_input, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calcIMC_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(div_top, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IMC_Avaluation_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentLayout.createSequentialGroup()
                        .addComponent(IMC_label, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(IMCResult_label, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(div_bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(label_title)
                .addGap(37, 37, 37)
                .addComponent(altura_label, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(altura_input, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(peso_input, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(calcIMC_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(div_top, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IMC_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IMCResult_label, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(div_bottom)
                .addGap(36, 36, 36)
                .addComponent(IMC_Avaluation_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout container2Layout = new javax.swing.GroupLayout(container2);
        container2.setLayout(container2Layout);
        container2Layout.setHorizontalGroup(
            container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container2Layout.createSequentialGroup()
                .addGroup(container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img_container2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(container2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        container2Layout.setVerticalGroup(
            container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(back_btn)
                .addGap(18, 18, 18)
                .addComponent(img_container2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(container2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void min_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min_btnMouseExited
        changeColor(min_btn, new Color(107,190,89));
    }//GEN-LAST:event_min_btnMouseExited

    private void min_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min_btnMouseEntered

        changeColor(min_btn, new Color(140, 223, 120));
    }//GEN-LAST:event_min_btnMouseEntered

    private void min_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min_btnMouseClicked
        this.setExtendedState(CalcBMISection.ICONIFIED);
    }//GEN-LAST:event_min_btnMouseClicked

    private void max_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max_btnMouseExited
        changeColor(max_btn, new Color(107,190,89));
    }//GEN-LAST:event_max_btnMouseExited

    private void max_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max_btnMouseEntered
        changeColor(max_btn, new Color(140, 223, 120));
    }//GEN-LAST:event_max_btnMouseEntered

    private void max_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max_btnMouseClicked
        if(this.getExtendedState() != CalcBMISection.MAXIMIZED_BOTH){
            this.setExtendedState(CalcBMISection.MAXIMIZED_BOTH);
        }else{
            this.setExtendedState(CalcBMISection.NORMAL);
        }
    }//GEN-LAST:event_max_btnMouseClicked

    private void close_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseExited
        changeColor(close_btn, new Color(107,190,89));
    }//GEN-LAST:event_close_btnMouseExited

    private void close_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseEntered
        changeColor(close_btn, Color.red);
    }//GEN-LAST:event_close_btnMouseEntered

    private void close_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseClicked
        dispose();
    }//GEN-LAST:event_close_btnMouseClicked

    private void calcIMC_btnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calcIMC_btnKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            double altura = Double.parseDouble(altura_input.getText());
            altura /= 100;
            double peso = Double.parseDouble(peso_input.getText());

            double IMC = peso / (altura*altura);

            DecimalFormat df = new DecimalFormat();
            String resultado = df.format(IMC);
            IMCResult_label.setText(resultado);

            if(IMC == Double.NaN){
                System.out.println("Tente de novo");
            }
            if(IMC < 18.4){
                IMC_Avaluation_label.setForeground(Color.red);
                IMC_Avaluation_label.setText("Voce está abaixo do peso!");

            }else if(IMC > 18.4 && IMC < 25 ){
                IMC_Avaluation_label.setForeground(Color.green );
                IMC_Avaluation_label.setText("Voce está no peso normal! Parabéns");

            }else if(IMC > 24 && IMC < 30){
                IMC_Avaluation_label.setForeground(Color.red);
                IMC_Avaluation_label.setText("Voce está em sobrepeso!");

            }else if(IMC > 29.9 && IMC < 35){
                IMC_Avaluation_label.setForeground(Color.red);
                IMC_Avaluation_label.setText("Obesidade grau 1! ");

            }else if(IMC > 34.9 && IMC < 40){
                IMC_Avaluation_label.setForeground(Color.red);
                IMC_Avaluation_label.setText("Obesidade grau 2! ");
            }
            else{
                IMC_Avaluation_label.setForeground(Color.red);
                IMC_Avaluation_label.setText("Obesidade mórbida!");

            }

        }
    }//GEN-LAST:event_calcIMC_btnKeyPressed

    private void calcIMC_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcIMC_btnActionPerformed
        double altura = Double.parseDouble(altura_input.getText());
        altura /= 100;
        double peso = Double.parseDouble(peso_input.getText());

        double IMC = peso / (altura*altura);

        DecimalFormat df = new DecimalFormat();
        String resultado = df.format(IMC);
        IMCResult_label.setText(resultado);

        if(IMC == Double.NaN){
            System.out.println("Tente de novo");
        }
        if(IMC < 18.4){
            IMC_Avaluation_label.setForeground(Color.red);
            IMC_Avaluation_label.setText("Voce está abaixo do peso!");

        }else if(IMC > 18.4 && IMC < 25 ){
            IMC_Avaluation_label.setForeground(Color.green );
            IMC_Avaluation_label.setText("Voce está no Peso normal! Parabéns");

        }else if(IMC > 24 && IMC < 30){
            IMC_Avaluation_label.setForeground(Color.red);
            IMC_Avaluation_label.setText("Voce está em sobrepeso!");

        }else if(IMC > 29.9 && IMC < 35){
            IMC_Avaluation_label.setForeground(Color.red);
            IMC_Avaluation_label.setText("Obesidade grau 1! ");

        }else if(IMC > 34.9 && IMC < 40){
            IMC_Avaluation_label.setForeground(Color.red);
            IMC_Avaluation_label.setText("Obesidade grau 2! ");
        }
        else{
            IMC_Avaluation_label.setForeground(Color.red);
            IMC_Avaluation_label.setText("Obesidade mórbida!");

        }
    }//GEN-LAST:event_calcIMC_btnActionPerformed

    private void peso_inputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_peso_inputKeyTyped
        peso_input.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
                    e.consume();
                }
            }
        });
    }//GEN-LAST:event_peso_inputKeyTyped

    private void peso_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peso_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peso_inputActionPerformed

    private void altura_inputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_altura_inputKeyTyped
        altura_input.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
                    e.consume();
                }
            }
        });
    }//GEN-LAST:event_altura_inputKeyTyped

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed

        new StartScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMI_Section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMI_Section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMI_Section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMI_Section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMI_Section().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMCResult_label;
    private javax.swing.JLabel IMC_Avaluation_label;
    private javax.swing.JLabel IMC_label;
    private javax.swing.JTextField altura_input;
    private javax.swing.JLabel altura_label;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton calcIMC_btn;
    private javax.swing.JPanel close_btn;
    private javax.swing.JLabel close_icon;
    private javax.swing.JPanel close_max_min_group;
    private javax.swing.JPanel container2;
    private javax.swing.JPanel content;
    private javax.swing.JLabel div_bottom;
    private javax.swing.JLabel div_top;
    private javax.swing.JPanel header;
    private javax.swing.JPanel img_container2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel label_title;
    private javax.swing.JPanel max_btn;
    private javax.swing.JPanel min_btn;
    private javax.swing.JLabel min_icon;
    private javax.swing.JTextField peso_input;
    // End of variables declaration//GEN-END:variables
}
