package fonts;

import java.awt.*;
import java.io.File;
import javax.swing.*;


/**
 *
 * @author MANUEL JAIME
 */
public class CalcBMISection extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    public CalcBMISection() {
        initComponents();
        
        CalcBMISection calc = new CalcBMISection();
        
        try {
            File font_family = new File("src/fonts/Outfit.ttf");
            Font font_title = Font.createFont(Font.TRUETYPE_FONT,font_family).deriveFont(32f);
            Font font_slogan = Font.createFont(Font.TRUETYPE_FONT,font_family).deriveFont(16f);
            Font font_copyright = Font.createFont(Font.TRUETYPE_FONT,font_family).deriveFont(12f);
            Font font = Font.createFont(Font.TRUETYPE_FONT,font_family).deriveFont(16f);
            
            height_label.setFont(font_title);
            weight_label.setFont(font_title);
            height_input.setFont(font_slogan);
            weigth_input.setFont(font);
            calcIMC_btn.setFont(font);
            IMC_answer.setFont(font);
            text_subtitle.setFont(font_copyright);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    void changeColor(JPanel hover, Color rand ){
        hover.setBackground(rand);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        close_max_min_group = new javax.swing.JPanel();
        close_btn = new javax.swing.JPanel();
        close_icon = new javax.swing.JLabel();
        max_btn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        min_btn = new javax.swing.JPanel();
        min_icon = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        back_btn = new javax.swing.JButton();
        img_container = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        weight_label = new javax.swing.JLabel();
        text_subtitle = new javax.swing.JLabel();
        height_input = new javax.swing.JTextField();
        height_label = new javax.swing.JLabel();
        weigth_input = new javax.swing.JTextField();
        calcIMC_btn = new javax.swing.JButton();
        div = new javax.swing.JLabel();
        div1 = new javax.swing.JLabel();
        IMC_answer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BMI Calculator - por Manuel Jaime");
        setUndecorated(true);
        setResizable(false);

        header.setBackground(new java.awt.Color(73, 158, 59));
        header.setPreferredSize(new java.awt.Dimension(800, 50));
        header.setRequestFocusEnabled(false);

        close_max_min_group.setBackground(new java.awt.Color(107, 190, 89));
        close_max_min_group.setPreferredSize(new java.awt.Dimension(150, 50));

        close_btn.setBackground(new java.awt.Color(107, 190, 89));
        close_btn.setPreferredSize(new java.awt.Dimension(50, 50));
        close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close_btnMouseExited(evt);
            }
        });
        close_btn.setLayout(new java.awt.BorderLayout());

        close_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fechar.png"))); // NOI18N
        close_btn.add(close_icon, java.awt.BorderLayout.CENTER);

        max_btn.setBackground(new java.awt.Color(107, 190, 89));
        max_btn.setPreferredSize(new java.awt.Dimension(50, 50));
        max_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                max_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                max_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                max_btnMouseExited(evt);
            }
        });
        max_btn.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/maximize-o-tamanho.png"))); // NOI18N
        max_btn.add(jLabel2, java.awt.BorderLayout.CENTER);

        min_btn.setBackground(new java.awt.Color(107, 190, 89));
        min_btn.setPreferredSize(new java.awt.Dimension(50, 50));
        min_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                min_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                min_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                min_btnMouseExited(evt);
            }
        });
        min_btn.setLayout(new java.awt.BorderLayout());

        min_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menos.png"))); // NOI18N
        min_btn.add(min_icon, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout close_max_min_groupLayout = new javax.swing.GroupLayout(close_max_min_group);
        close_max_min_group.setLayout(close_max_min_groupLayout);
        close_max_min_groupLayout.setHorizontalGroup(
            close_max_min_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, close_max_min_groupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(min_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(max_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        close_max_min_groupLayout.setVerticalGroup(
            close_max_min_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(close_max_min_groupLayout.createSequentialGroup()
                .addGroup(close_max_min_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(max_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(min_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 728, Short.MAX_VALUE)
                .addComponent(close_max_min_group, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close_max_min_group, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        container.setBackground(new java.awt.Color(255, 255, 255));

        back_btn.setBackground(new java.awt.Color(26, 185, 33));
        back_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setText("Voltar");
        back_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        img_container.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modified/imc-section-img.png"))); // NOI18N

        javax.swing.GroupLayout img_containerLayout = new javax.swing.GroupLayout(img_container);
        img_container.setLayout(img_containerLayout);
        img_containerLayout.setHorizontalGroup(
            img_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        img_containerLayout.setVerticalGroup(
            img_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, img_containerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        content.setBackground(new java.awt.Color(51, 51, 51));

        weight_label.setForeground(new java.awt.Color(255, 255, 255));
        weight_label.setText("Peso (kg)");
        weight_label.setPreferredSize(new java.awt.Dimension(80, 16));

        text_subtitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        text_subtitle.setForeground(new java.awt.Color(255, 255, 255));
        text_subtitle.setText("Vamos Calcular o seu IMC !");

        height_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                height_inputActionPerformed(evt);
            }
        });

        height_label.setForeground(new java.awt.Color(255, 255, 255));
        height_label.setText("Altura (cm)");

        calcIMC_btn.setBackground(new java.awt.Color(40, 126, 29));
        calcIMC_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        calcIMC_btn.setForeground(new java.awt.Color(255, 255, 255));
        calcIMC_btn.setText("Calcular IMC");
        calcIMC_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        div.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        div1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        IMC_answer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(div, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(height_label, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(weight_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(height_input, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(weigth_input, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(text_subtitle))
                        .addComponent(calcIMC_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(div1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(IMC_answer, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(text_subtitle)
                .addGap(27, 27, 27)
                .addComponent(height_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(height_input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(weight_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weigth_input, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(calcIMC_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(div)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IMC_answer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(div1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(img_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(back_btn)
                .addGap(18, 18, 18)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(img_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void close_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseEntered
        changeColor(close_btn, Color.red);
    }//GEN-LAST:event_close_btnMouseEntered

    private void close_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseExited
         changeColor(close_btn, new Color(107,190,89));
    }//GEN-LAST:event_close_btnMouseExited

    private void close_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseClicked
        dispose();
    }//GEN-LAST:event_close_btnMouseClicked

    private void max_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max_btnMouseEntered
         changeColor(max_btn, new Color(140, 223, 120));
    }//GEN-LAST:event_max_btnMouseEntered

    private void max_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max_btnMouseExited
         changeColor(max_btn, new Color(107,190,89));
    }//GEN-LAST:event_max_btnMouseExited

    private void max_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max_btnMouseClicked
        if(this.getExtendedState() != CalcBMISection.MAXIMIZED_BOTH){
            this.setExtendedState(CalcBMISection.MAXIMIZED_BOTH);
        }else{
            this.setExtendedState(CalcBMISection.NORMAL);
        }
    }//GEN-LAST:event_max_btnMouseClicked

    private void min_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min_btnMouseEntered
        
         changeColor(min_btn, new Color(140, 223, 120));
    }//GEN-LAST:event_min_btnMouseEntered

    private void min_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min_btnMouseExited
         changeColor(min_btn, new Color(107,190,89));
    }//GEN-LAST:event_min_btnMouseExited

    private void min_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min_btnMouseClicked
        this.setExtendedState(CalcBMISection.ICONIFIED);
    }//GEN-LAST:event_min_btnMouseClicked

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed

        new HomeScreen().show();
        dispose();
        
    }//GEN-LAST:event_back_btnActionPerformed

    private void height_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_height_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_height_inputActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcBMISection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcBMISection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcBMISection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcBMISection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcBMISection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMC_answer;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton calcIMC_btn;
    private javax.swing.JPanel close_btn;
    private javax.swing.JLabel close_icon;
    private javax.swing.JPanel close_max_min_group;
    private javax.swing.JPanel container;
    private javax.swing.JPanel content;
    private javax.swing.JLabel div;
    private javax.swing.JLabel div1;
    private javax.swing.JPanel header;
    private javax.swing.JTextField height_input;
    private javax.swing.JLabel height_label;
    private javax.swing.JPanel img_container;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel max_btn;
    private javax.swing.JPanel min_btn;
    private javax.swing.JLabel min_icon;
    private javax.swing.JLabel text_subtitle;
    private javax.swing.JLabel weight_label;
    private javax.swing.JTextField weigth_input;
    // End of variables declaration//GEN-END:variables
}
