package fonts;
import java.awt.*;
import javax.swing.*;


/**
 *
 * @author MANUEL JAIME
 */
public class HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    public HomeScreen() {
        initComponents();
    }
    
    void changeColor(JPanel hover, Color rand ){
        hover.setBackground(rand);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        close_max_min_group = new javax.swing.JPanel();
        close_btn = new javax.swing.JPanel();
        close_icon = new javax.swing.JLabel();
        max_btn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        min_btn = new javax.swing.JPanel();
        min_icon = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        img_container = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        text_subtitle = new javax.swing.JLabel();
        about_btn = new javax.swing.JButton();
        jButton133 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BMI Calculator - por Manuel Jaime");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setUndecorated(true);
        setResizable(false);

        header.setBackground(new java.awt.Color(73, 158, 59));
        header.setPreferredSize(new java.awt.Dimension(800, 50));
        header.setRequestFocusEnabled(false);

        close_max_min_group.setBackground(new java.awt.Color(107, 190, 89));
        close_max_min_group.setPreferredSize(new java.awt.Dimension(150, 50));

        close_btn.setBackground(new java.awt.Color(107, 190, 89));
        close_btn.setPreferredSize(new java.awt.Dimension(50, 50));
        close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close_btnMouseExited(evt);
            }
        });
        close_btn.setLayout(new java.awt.BorderLayout());

        close_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fechar.png"))); // NOI18N
        close_btn.add(close_icon, java.awt.BorderLayout.CENTER);

        max_btn.setBackground(new java.awt.Color(107, 190, 89));
        max_btn.setPreferredSize(new java.awt.Dimension(50, 50));
        max_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                max_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                max_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                max_btnMouseExited(evt);
            }
        });
        max_btn.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/maximize-o-tamanho.png"))); // NOI18N
        max_btn.add(jLabel2, java.awt.BorderLayout.CENTER);

        min_btn.setBackground(new java.awt.Color(107, 190, 89));
        min_btn.setPreferredSize(new java.awt.Dimension(50, 50));
        min_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                min_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                min_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                min_btnMouseExited(evt);
            }
        });
        min_btn.setLayout(new java.awt.BorderLayout());

        min_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menos.png"))); // NOI18N
        min_btn.add(min_icon, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout close_max_min_groupLayout = new javax.swing.GroupLayout(close_max_min_group);
        close_max_min_group.setLayout(close_max_min_groupLayout);
        close_max_min_groupLayout.setHorizontalGroup(
            close_max_min_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, close_max_min_groupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(min_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(max_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        close_max_min_groupLayout.setVerticalGroup(
            close_max_min_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(close_max_min_groupLayout.createSequentialGroup()
                .addGroup(close_max_min_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(max_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(min_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 748, Short.MAX_VALUE)
                .addComponent(close_max_min_group, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close_max_min_group, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        container.setBackground(new java.awt.Color(255, 255, 255));

        img_container.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modified/home-img.png"))); // NOI18N

        javax.swing.GroupLayout img_containerLayout = new javax.swing.GroupLayout(img_container);
        img_container.setLayout(img_containerLayout);
        img_containerLayout.setHorizontalGroup(
            img_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, img_containerLayout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        img_containerLayout.setVerticalGroup(
            img_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );

        text_subtitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        text_subtitle.setText("Bem_vindos ao BMI Calculator");

        about_btn.setBackground(new java.awt.Color(26, 185, 33));
        about_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        about_btn.setForeground(new java.awt.Color(255, 255, 255));
        about_btn.setText("Sobre");
        about_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_btnActionPerformed(evt);
            }
        });

        jButton133.setText("jButton1");
        jButton133.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton133ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(img_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(text_subtitle))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(about_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButton133))))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img_container, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(text_subtitle)
                .addGap(50, 50, 50)
                .addComponent(jButton133)
                .addGap(63, 63, 63)
                .addComponent(about_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void close_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseEntered
        changeColor(close_btn, Color.red);
    }//GEN-LAST:event_close_btnMouseEntered

    private void close_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseExited
         changeColor(close_btn, new Color(107,190,89));
    }//GEN-LAST:event_close_btnMouseExited

    private void close_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseClicked
        dispose();
    }//GEN-LAST:event_close_btnMouseClicked

    private void max_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max_btnMouseEntered
         changeColor(max_btn, new Color(140, 223, 120));
    }//GEN-LAST:event_max_btnMouseEntered

    private void max_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max_btnMouseExited
         changeColor(max_btn, new Color(107,190,89));
    }//GEN-LAST:event_max_btnMouseExited

    private void max_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max_btnMouseClicked
        if(this.getExtendedState() != HomeScreen.MAXIMIZED_BOTH){
            this.setExtendedState(HomeScreen.MAXIMIZED_BOTH);
        }else{
            this.setExtendedState(HomeScreen.NORMAL);
        }
    }//GEN-LAST:event_max_btnMouseClicked

    private void min_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min_btnMouseEntered
        
         changeColor(min_btn, new Color(140, 223, 120));
    }//GEN-LAST:event_min_btnMouseEntered

    private void min_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min_btnMouseExited
         changeColor(min_btn, new Color(107,190,89));
    }//GEN-LAST:event_min_btnMouseExited

    private void min_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min_btnMouseClicked
        this.setExtendedState(HomeScreen.ICONIFIED);
    }//GEN-LAST:event_min_btnMouseClicked

    private void about_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_about_btnActionPerformed

    private void jButton133ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton133ActionPerformed
        new CalcBMISection().show();
        dispose();
    }//GEN-LAST:event_jButton133ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about_btn;
    private javax.swing.JPanel close_btn;
    private javax.swing.JLabel close_icon;
    private javax.swing.JPanel close_max_min_group;
    private javax.swing.JPanel container;
    private javax.swing.JPanel header;
    private javax.swing.JPanel img_container;
    private javax.swing.JButton jButton133;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel max_btn;
    private javax.swing.JPanel min_btn;
    private javax.swing.JLabel min_icon;
    private javax.swing.JLabel text_subtitle;
    // End of variables declaration//GEN-END:variables
}
