package main;
import java.awt.*;
import java.io.*;

/**
 *
 * @author MANUEL JAIME
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        
        setIcon();
        
        // try...catch para a fonte geral
        try {
            File font_family = new File("src/fonts/Outfit-Regular.ttf");
            
            Font font_slogan = Font.createFont(Font.TRUETYPE_FONT,font_family).deriveFont(16f);
            Font font_copyright = Font.createFont(Font.TRUETYPE_FONT,font_family).deriveFont(12f);
            Font font = Font.createFont(Font.TRUETYPE_FONT,font_family).deriveFont(18f);
            
            
            splash_slogan.setFont(font_slogan);
            progress_bar.setFont(font);
            progress_value.setFont(font);
            processing_text.setFont(font);
            copyright.setFont(font_copyright);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        // try...catch para fonte do titulo
        try {
            File font_family_bold = new File("src/fonts/Outfit-Bold.ttf");
            Font font_title = Font.createFont(Font.TRUETYPE_FONT,font_family_bold).deriveFont(32f);
            splash_title.setFont(font_title);
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        splash_img = new javax.swing.JLabel();
        progress_bar = new javax.swing.JProgressBar();
        progress_value = new javax.swing.JLabel();
        splash_title = new javax.swing.JLabel();
        splash_slogan = new javax.swing.JLabel();
        processing_text = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BMI Calculator - por Manuel Jaime");
        setUndecorated(true);

        container.setBackground(new java.awt.Color(255, 255, 255));

        splash_img.setBackground(new java.awt.Color(255, 255, 255));
        splash_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        splash_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modified/splash-img (init-size).png"))); // NOI18N

        progress_bar.setForeground(new java.awt.Color(73, 158, 59));

        progress_value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        progress_value.setText("0%");

        splash_title.setBackground(new java.awt.Color(73, 158, 59));
        splash_title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        splash_title.setForeground(new java.awt.Color(73, 158, 59));
        splash_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        splash_title.setText("BMI Calculator");

        splash_slogan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        splash_slogan.setText("Sinta-se saudável!");

        processing_text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        processing_text.setText("A processar...");

        copyright.setText("Manuel Jaime 2024 - Todos os direitos reservados");

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splash_img, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(copyright))
                            .addGroup(containerLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(containerLayout.createSequentialGroup()
                                        .addComponent(processing_text)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(progress_value))
                                    .addComponent(progress_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(containerLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(splash_title, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(splash_slogan)
                        .addGap(140, 140, 140))))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splash_img, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(splash_title, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splash_slogan)
                .addGap(58, 58, 58)
                .addComponent(progress_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(progress_value)
                    .addComponent(processing_text))
                .addGap(94, 94, 94)
                .addComponent(copyright)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(762, 467));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        SplashScreen splash = new SplashScreen();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                splash.setVisible(true);
            }
        });
        
        try {
            
            for(int i = 0; i <= 100; i++){
                Thread.sleep(40);
                splash.progress_bar.setValue(i);
                splash.progress_value.setText(Integer.toString(i) + "%");
                
                if(splash.progress_bar.getValue() >= 90){
                    splash.processing_text.setText("Bem-vindo");
                }
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        splash.setVisible(false);
        new StartScreen().setVisible(true);
        splash.dispose();
    }
    
    void setIcon(){
        // setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("src/icons/logo-1.png")));
        setIconImage(Toolkit.getDefaultToolkit().getImage("src/icons/logo-1.png"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JLabel copyright;
    private javax.swing.JLabel processing_text;
    private javax.swing.JProgressBar progress_bar;
    private javax.swing.JLabel progress_value;
    private javax.swing.JLabel splash_img;
    private javax.swing.JLabel splash_slogan;
    private javax.swing.JLabel splash_title;
    // End of variables declaration//GEN-END:variables

   
}
